/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayOpLevelRouteImport } from './routes/play.$op.$level'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayOpLevelRoute = PlayOpLevelRouteImport.update({
  id: '/play/$op/$level',
  path: '/play/$op/$level',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ranking': typeof RankingRoute
  '/play/$op/$level': typeof PlayOpLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ranking': typeof RankingRoute
  '/play/$op/$level': typeof PlayOpLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ranking': typeof RankingRoute
  '/play/$op/$level': typeof PlayOpLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ranking' | '/play/$op/$level'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ranking' | '/play/$op/$level'
  id: '__root__' | '/' | '/ranking' | '/play/$op/$level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RankingRoute: typeof RankingRoute
  PlayOpLevelRoute: typeof PlayOpLevelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$op/$level': {
      id: '/play/$op/$level'
      path: '/play/$op/$level'
      fullPath: '/play/$op/$level'
      preLoaderRoute: typeof PlayOpLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RankingRoute: RankingRoute,
  PlayOpLevelRoute: PlayOpLevelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
